import { createElement, Check, CheckCheck, CheckCircle, X, XCircle, Plus, Minus, Menu, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Pencil, Trash2, Link, Upload, Download, RotateCcw, Target, Vote, Trophy, FileText, Clipboard, Lock, User, Search, Star, Crown, PartyPopper, Lightbulb, Puzzle, Zap, Globe, Heart, Sun, Moon, Palette, Eye, EyeOff, Users, RefreshCcw, Maximize2, Circle, Share2, Mail, Camera, AlertTriangle, Info, Smartphone, Pen, Ruler, Shuffle, Settings, LogOut, Home, ExternalLink, GripVertical, FileDown, FileUp, HelpCircle, BookOpen, Hash, UserRound, Hand, GalleryVerticalEnd, SquareChartGantt, ListFilter, QrCode, List, Filter, SlidersHorizontal, Sparkles, Rabbit, Tally5, Square, CheckSquare, TriangleAlert, Undo2, BarChart3, FolderOpen, HardDrive } from 'lucide';

const ICON_MAP = {
  check: Check,
  'check-check': CheckCheck,
  'check-circle': CheckCircle,
  x: X,
  'x-circle': XCircle,
  plus: Plus,
  minus: Minus,
  menu: Menu,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  pencil: Pencil,
  'trash-2': Trash2,
  link: Link,
  upload: Upload,
  download: Download,
  'rotate-ccw': RotateCcw,
  target: Target,
  vote: Vote,
  trophy: Trophy,
  'file-text': FileText,
  clipboard: Clipboard,
  lock: Lock,
  user: User,
  search: Search,
  star: Star,
  crown: Crown,
  'party-popper': PartyPopper,
  lightbulb: Lightbulb,
  puzzle: Puzzle,
  zap: Zap,
  globe: Globe,
  heart: Heart,
  sun: Sun,
  moon: Moon,
  palette: Palette,
  eye: Eye,
  'eye-off': EyeOff,
  users: Users,
  'refresh-ccw': RefreshCcw,
  'maximize-2': Maximize2,
  circle: Circle,
  'share-2': Share2,
  mail: Mail,
  camera: Camera,
  'alert-triangle': AlertTriangle,
  info: Info,
  smartphone: Smartphone,
  pen: Pen,
  ruler: Ruler,
  shuffle: Shuffle,
  settings: Settings,
  'log-out': LogOut,
  home: Home,
  'external-link': ExternalLink,
  'grip-vertical': GripVertical,
  'file-down': FileDown,
  'file-up': FileUp,
  'help-circle': HelpCircle,
  'book-open': BookOpen,
  hash: Hash,
  'user-round': UserRound,
  hand: Hand,
  'gallery-vertical-end': GalleryVerticalEnd,
  'square-chart-gantt': SquareChartGantt,
  'list-filter': ListFilter,
  'qr-code': QrCode,
  list: List,
  filter: Filter,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  rabbit: Rabbit,
  'tally-5': Tally5,
  square: Square,
  'check-square': CheckSquare,
  'triangle-alert': TriangleAlert,
  undo2: Undo2,
  'bar-chart': BarChart3,
  'folder-open': FolderOpen,
  'hard-drive': HardDrive,
};

ICON_MAP['download-icon'] = Download;
ICON_MAP['upload-icon'] = Upload;

export function getNode(name) {
  return ICON_MAP[name];
}

export function svg(name, size = 16, color = 'currentColor') {
  const iconNode = ICON_MAP[name];
  if (!iconNode) return '';
  return createElement(iconNode, { width: size, height: size, stroke: color }).outerHTML;
}
