const components = {
  "AppShell": "AppComponents",
  "ByTeamView": "AppComponents",
  "CompareView": "AppComponents",
  "DashboardView": "AppComponents",
  "HelpView": "AppComponents",
  "MyAssignmentView": "AppComponents",
  "SettingsView": "AppComponents",
  "Button": "Visual",
  "Link": "Visual",
  "Loading": "Visual",
  "MemberChip": "Visual",
  "Modal": "Visual",
  "MultiRoute": "Visual",
  "Navbar": "Visual",
  "NotFound": "Visual",
  "Route": "Visual",
  "StatusBadge": "Visual",
  "ThemeSwitcher": "Visual",
  "Toast": "Visual",
  "AssignmentService": "Service",
  "ConfirmActionModal": "Service",
  "DragDropService": "Service",
  "FetchManager": "Service",
  "FileDownloadService": "Service",
  "IndexedDbManager": "Service",
  "LocalStorageManager": "Service",
  "ResolutionService": "Service",
  "RosterService": "Service",
  "SettingsService": "Service",
  "ToastProvider": "Service",
  "Providers": "AppServices"
};

export default components;
