/* Auto-generated by slice types generate. Do not edit manually. */

export interface AppShellProps {
  [key: string]: unknown;
}

export interface BienvenidaModalProps {
  [key: string]: unknown;
}

export interface ButtonProps {
  [key: string]: unknown;
  customColor?: Record<string, unknown>;
  icon?: Record<string, unknown>;
  onClick?: (...args: unknown[]) => unknown;
  onClickCallback?: (...args: unknown[]) => unknown;
  size?: 'md' | 'sm';
  value?: string;
  variant?: 'filled' | 'outlined' | 'ghost' | 'soft' | 'danger';
}

export interface CarouselViewProps {
  [key: string]: unknown;
}

export interface ChartServiceProps {
  [key: string]: unknown;
}

export interface CheckboxProps {
  [key: string]: unknown;
  checked?: boolean;
  customColor?: Record<string, unknown>;
  disabled?: boolean;
  label?: string;
  labelPlacement?: string;
}

export interface CompareCarouselProps {
  [key: string]: unknown;
}

export interface CompareNotesModalProps {
  [key: string]: unknown;
}

export interface CompareViewProps {
  [key: string]: unknown;
}

export interface CompressionServiceProps {
  [key: string]: unknown;
}

export interface ConfirmActionModalProps {
  [key: string]: unknown;
}

export interface ConsensoServiceProps {
  [key: string]: unknown;
}

export interface DashboardViewProps {
  [key: string]: unknown;
}

export interface DomServiceProps {
  [key: string]: unknown;
}

export interface DragDropServiceProps {
  [key: string]: unknown;
}

export interface DropDownProps {
  [key: string]: unknown;
  label?: string;
  options?: unknown[];
}

export interface EmptyStateProps {
  [key: string]: unknown;
  buttonLabel?: string;
  buttonOnClick?: (...args: unknown[]) => unknown;
  buttonRoute?: string;
  description?: string;
  icon?: string;
  title?: string;
}

export interface EnhancedEditorProps {
  [key: string]: unknown;
}

export interface ExportRespuestasModalProps {
  [key: string]: unknown;
}

export interface ExportServiceProps {
  [key: string]: unknown;
}

export interface FetchManagerProps {
  [key: string]: unknown;
}

export interface FileDownloadServiceProps {
  [key: string]: unknown;
}

export interface FinalTallyProps {
  [key: string]: unknown;
}

export interface HtmlServiceProps {
  [key: string]: unknown;
}

export interface IconProps {
  [key: string]: unknown;
  color?: string;
  name?: string;
  size?: string;
}

export interface IconProviderProps {
  [key: string]: unknown;
}

export interface ImportDropProps {
  [key: string]: unknown;
}

export interface IndexedDbManagerProps {
  [key: string]: unknown;
}

export interface InputProps {
  [key: string]: unknown;
  conditions?: Record<string, unknown>;
  disabled?: boolean;
  placeholder?: string;
  required?: boolean;
  secret?: boolean;
  type?: string;
  value?: string;
}

export interface LandingViewProps {
  [key: string]: unknown;
}

export interface LinkProps {
  [key: string]: unknown;
}

export interface LoadingProps {
  [key: string]: unknown;
  active?: boolean;
  container?: Record<string, unknown>;
  isActive?: boolean;
}

export interface LocalStorageManagerProps {
  [key: string]: unknown;
}

export interface MisRespuestasViewProps {
  [key: string]: unknown;
}

export interface ModalProps {
  [key: string]: unknown;
  customColor?: Record<string, unknown>;
  dismissable?: boolean;
  draggable?: boolean;
  maxWidth?: string;
  onClose?: (...args: unknown[]) => unknown;
  open?: boolean;
  resizable?: boolean;
  title?: string;
  width?: string;
}

export interface MultiRouteProps {
  [key: string]: unknown;
}

export interface NavbarProps {
  [key: string]: unknown;
  buttons?: unknown[];
  direction?: string;
  items?: unknown[];
  logo?: Record<string, unknown>;
  position?: string;
}

export interface NotFoundProps {
  [key: string]: unknown;
}

export interface OpcionChipProps {
  [key: string]: unknown;
  draggable?: boolean;
  opcion?: Record<string, unknown>;
}

export interface OpcionRowProps {
  [key: string]: unknown;
  opcion?: Record<string, unknown>;
}

export interface PlantillaBuilderViewProps {
  [key: string]: unknown;
}

export interface PlantillaServiceProps {
  [key: string]: unknown;
}

export interface PorTemaViewProps {
  [key: string]: unknown;
}

export interface ProfileBubbleProps {
  [key: string]: unknown;
}

export interface ProvidersProps {
  [key: string]: unknown;
}

export interface RespuestasImportServiceProps {
  [key: string]: unknown;
}

export interface RespuestasRankingViewProps {
  [key: string]: unknown;
}

export interface RespuestasServiceProps {
  [key: string]: unknown;
}

export interface RespuestasTextoViewProps {
  [key: string]: unknown;
}

export interface RespuestasViewProps {
  [key: string]: unknown;
}

export interface RespuestasVotacionViewProps {
  [key: string]: unknown;
}

export interface ResumenFinalViewProps {
  [key: string]: unknown;
}

export interface RouteProps {
  [key: string]: unknown;
}

export interface SelectProps {
  [key: string]: unknown;
  clearable?: boolean;
  disabled?: boolean;
  label?: string;
  multiple?: boolean;
  onChange?: (...args: unknown[]) => unknown;
  onOptionSelect?: (...args: unknown[]) => unknown;
  options?: unknown[];
  placeholder?: string;
  searchable?: boolean;
  visibleProp?: string;
}

export interface SettingsServiceProps {
  [key: string]: unknown;
}

export interface ShareConsensoModalProps {
  [key: string]: unknown;
}

export interface SharePlantillaModalProps {
  [key: string]: unknown;
}

export interface SoundServiceProps {
  [key: string]: unknown;
}

export interface StatusBadgeProps {
  [key: string]: unknown;
  label?: string;
  status?: 'ok' | 'under' | 'over' | 'empty';
}

export interface StoreServiceProps {
  [key: string]: unknown;
}

export interface SwitchProps {
  [key: string]: unknown;
  checked?: boolean;
  customColor?: Record<string, unknown>;
  disabled?: boolean;
  label?: string;
  labelPlacement?: string;
  onChange?: (...args: unknown[]) => unknown;
  toggle?: (...args: unknown[]) => unknown;
}

export interface SynthTextoModalProps {
  [key: string]: unknown;
}

export interface TabsProps {
  [key: string]: unknown;
  activeTab?: string;
  items?: { id: string; label: string; }[];
  onChange?: (...args: unknown[]) => unknown;
  onTabChange?: (...args: unknown[]) => unknown;
  variant?: string;
}

export interface TemaRowProps {
  [key: string]: unknown;
  tema?: Record<string, unknown>;
}

export interface TestHarnessProps {
  [key: string]: unknown;
}

export interface TextCompareCardsProps {
  [key: string]: unknown;
}

export interface TextoCardProps {
  [key: string]: unknown;
}

export interface ThemeSwitcherProps {
  [key: string]: unknown;
  label?: string;
  onChange?: (...args: unknown[]) => unknown;
  themes?: unknown[];
  variant?: 'button' | 'menu-item';
}

export interface ToastProps {
  [key: string]: unknown;
  customColor?: Record<string, unknown>;
  dismissable?: boolean;
  duration?: number;
  message?: string;
  type?: string;
}

export interface ToastProviderProps {
  [key: string]: unknown;
}

export interface ToolTipProps {
  [key: string]: unknown;
  customColor?: Record<string, unknown>;
  hideDelay?: number;
  maxWidth?: number;
  offset?: number;
  placement?: string;
  showDelay?: number;
  text?: string;
}

export interface TopBarProps {
  [key: string]: unknown;
}

export interface UserMenuProps {
  [key: string]: unknown;
}

export interface ViewHeaderProps {
  [key: string]: unknown;
  subtitle?: string;
  title?: string;
}

export interface SliceComponentPropsMap {
  AppShell: AppShellProps;
  BienvenidaModal: BienvenidaModalProps;
  Button: ButtonProps;
  CarouselView: CarouselViewProps;
  ChartService: ChartServiceProps;
  Checkbox: CheckboxProps;
  CompareCarousel: CompareCarouselProps;
  CompareNotesModal: CompareNotesModalProps;
  CompareView: CompareViewProps;
  CompressionService: CompressionServiceProps;
  ConfirmActionModal: ConfirmActionModalProps;
  ConsensoService: ConsensoServiceProps;
  DashboardView: DashboardViewProps;
  DomService: DomServiceProps;
  DragDropService: DragDropServiceProps;
  DropDown: DropDownProps;
  EmptyState: EmptyStateProps;
  EnhancedEditor: EnhancedEditorProps;
  ExportRespuestasModal: ExportRespuestasModalProps;
  ExportService: ExportServiceProps;
  FetchManager: FetchManagerProps;
  FileDownloadService: FileDownloadServiceProps;
  FinalTally: FinalTallyProps;
  HtmlService: HtmlServiceProps;
  Icon: IconProps;
  IconProvider: IconProviderProps;
  ImportDrop: ImportDropProps;
  IndexedDbManager: IndexedDbManagerProps;
  Input: InputProps;
  LandingView: LandingViewProps;
  Link: LinkProps;
  Loading: LoadingProps;
  LocalStorageManager: LocalStorageManagerProps;
  MisRespuestasView: MisRespuestasViewProps;
  Modal: ModalProps;
  MultiRoute: MultiRouteProps;
  Navbar: NavbarProps;
  NotFound: NotFoundProps;
  OpcionChip: OpcionChipProps;
  OpcionRow: OpcionRowProps;
  PlantillaBuilderView: PlantillaBuilderViewProps;
  PlantillaService: PlantillaServiceProps;
  PorTemaView: PorTemaViewProps;
  ProfileBubble: ProfileBubbleProps;
  Providers: ProvidersProps;
  RespuestasImportService: RespuestasImportServiceProps;
  RespuestasRankingView: RespuestasRankingViewProps;
  RespuestasService: RespuestasServiceProps;
  RespuestasTextoView: RespuestasTextoViewProps;
  RespuestasView: RespuestasViewProps;
  RespuestasVotacionView: RespuestasVotacionViewProps;
  ResumenFinalView: ResumenFinalViewProps;
  Route: RouteProps;
  Select: SelectProps;
  SettingsService: SettingsServiceProps;
  ShareConsensoModal: ShareConsensoModalProps;
  SharePlantillaModal: SharePlantillaModalProps;
  SoundService: SoundServiceProps;
  StatusBadge: StatusBadgeProps;
  StoreService: StoreServiceProps;
  Switch: SwitchProps;
  SynthTextoModal: SynthTextoModalProps;
  Tabs: TabsProps;
  TemaRow: TemaRowProps;
  TestHarness: TestHarnessProps;
  TextCompareCards: TextCompareCardsProps;
  TextoCard: TextoCardProps;
  ThemeSwitcher: ThemeSwitcherProps;
  Toast: ToastProps;
  ToastProvider: ToastProviderProps;
  ToolTip: ToolTipProps;
  TopBar: TopBarProps;
  UserMenu: UserMenuProps;
  ViewHeader: ViewHeaderProps;
}

export type SliceComponentName = keyof SliceComponentPropsMap;
export type SliceDynamicElement = HTMLElement & Record<string, any>;

export interface SliceEventRegistry {
  "confirm:request": { title: string; message: string; confirmLabel: string; cancelLabel: string; danger: boolean; inputLabel: string; inputPlaceholder: string; inputValue: string; onConfirm: (...args: unknown[]) => unknown; onCancel: (...args: unknown[]) => unknown };
  "tema:move": { temaId: string; direction: number };
  "toast:show": { message: string; type: string };
}

type SliceEventCatalog = Record<string, { description?: string; payload?: unknown }>;

// name the payload is enforced; for any other (unknown / framework / dynamic
// context:* events) it stays permissive. A plain string-fallback overload
// would swallow wrong-payload calls and defeat the whole point.
type SliceEventData<K extends string> = K extends keyof SliceEventRegistry ? SliceEventRegistry[K] : unknown;
type SliceEventArgs<K extends string> = K extends keyof SliceEventRegistry
  ? (SliceEventRegistry[K] extends void ? [] : [SliceEventRegistry[K]])
  : unknown[];

export interface SliceTypedEventBinding {
  subscribe<K extends string>(eventName: K, callback: (data: SliceEventData<K>) => void): string | null;
  subscribeOnce<K extends string>(eventName: K, callback: (data: SliceEventData<K>) => void): string | null;
  emit<K extends string>(eventName: K, ...data: SliceEventArgs<K>): void;
  register(namespace: string, catalog: SliceEventCatalog): unknown;
  register(catalog: SliceEventCatalog): unknown;
}

export interface SliceTypedEventManager {
  init(): boolean;
  subscribe<K extends string>(eventName: K, callback: (data: SliceEventData<K>) => void, options?: { component?: HTMLElement }): string | null;
  subscribeOnce<K extends string>(eventName: K, callback: (data: SliceEventData<K>) => void, options?: { component?: HTMLElement }): string | null;
  unsubscribe(eventName: string, subscriptionId: string): boolean;
  emit<K extends string>(eventName: K, ...data: SliceEventArgs<K>): void;
  bind(component: HTMLElement): SliceTypedEventBinding | null;
  cleanupComponent(sliceId: string): number;
  hasSubscribers(eventName: string): boolean;
  subscriberCount(eventName: string): number;
  isDeclared(eventName: string): boolean;
  namespaceOf(eventName: string): string | null;
  register(namespace: string, catalog: SliceEventCatalog): SliceTypedEventManager;
  register(catalog: SliceEventCatalog): SliceTypedEventManager;
  clear(): void;
}

declare global {
  const slice: SliceBuildApi;

  interface Event {
    detail: any;
    key: any;
    request: any;
    waitUntil: any;
    respondWith: any;
    target: any;
    currentTarget: any;
  }

  interface Element {
    querySelector<E extends Element = HTMLElement>(selectors: string): E | null;
    querySelectorAll<E extends Element = HTMLElement>(selectors: string): NodeListOf<E>;
  }
  interface HTMLElement {
    [key: string]: any;
  }
  interface EventTarget {
    [key: string]: any;
  }

  interface SliceBuildApi {
    [key: string]: any;
    build<K extends SliceComponentName>(
      name: K,
      props?: SliceComponentPropsMap[K]
    ): Promise<SliceDynamicElement | null>;
    events: SliceTypedEventManager;
  }
}

declare module 'slicejs-web-framework' {
  interface SliceApi {
    build<K extends SliceComponentName>(
      name: K,
      props?: SliceComponentPropsMap[K]
    ): Promise<SliceDynamicElement | null>;
    getComponent<K extends SliceComponentName>(
      componentSliceId: K | `${K}-${string}`
    ): SliceDynamicElement | undefined;
    getComponent<T extends SliceDynamicElement = SliceDynamicElement>(
      componentSliceId: string
    ): T | undefined;
    events: SliceTypedEventManager;
  }
}

export {};
